# Cloud Build configuration for GA4 Analytics Agent
# Triggers on push to master branch or manual trigger

steps:
  # Step 1: Build the Docker image with cache busting
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'CACHE_BUST=$BUILD_ID'
      - '-t'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/ga4-analytics-agent:$BUILD_ID'
      - '-t'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/ga4-analytics-agent:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/ga4-analytics-agent'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ga4-analytics-agent'
      - '--image=europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/ga4-analytics-agent:latest'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--set-env-vars=GA4_MCP_SERVER_URL=${_GA4_MCP_SERVER_URL},SENDER_EMAIL=${_SENDER_EMAIL}'
      - '--set-secrets=GMAIL_OAUTH_CLIENT_ID=gmail-oauth-client-id:latest,GMAIL_OAUTH_CLIENT_SECRET=gmail-oauth-client-secret:latest,GMAIL_OAUTH_REFRESH_TOKEN=gmail-oauth-refresh-token:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Substitution variables (can be set in trigger or manually)
substitutions:
  _GA4_MCP_SERVER_URL: 'https://ga4-http-api-1062626335546.europe-west1.run.app'
  _SENDER_EMAIL: 'noreply@avisia.fr'

# Images to be pushed to Artifact Registry
images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/ga4-analytics-agent:$BUILD_ID'
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/ga4-analytics-agent:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s  # 20 minutes
